// const cards = [
//   {
//     imageUrl: 'https://cdn.shopify.com/s/files/1/2090/1179/products/STL181613.jpg?v=1613777309',
//     badge: 'new',
//     publisher: 'DC comics',
//     title: 'Sensational Wonder Woman Vol 1 1',
//     reviewCount: 34,
//     rating: 4,
//     characters: ['Wonder Woman', 'Hawkgirl', 'Doctor Psycho'],
//   },
//   {
//     imageUrl:
//       'https://cdn.shopify.com/s/files/1/0040/6624/6769/products/1986561_xl_800x800.jpg?v=1616602343',
//     publisher: 'DC comics',
//     title: 'The Joker Vol 2 1',
//     reviewCount: 5,
//     rating: 5,
//     characters: ['Batman ', 'Joker', 'Bane'],
//   },
//   {
//     imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/A1hznmL41KL.jpg',
//     publisher: 'DC comics',
//     title: 'Suicide Squad Vol. 7: Drain the Swamp',
//     reviewCount: 31,
//     rating: 5,
//     characters: ['Harley Quinn', 'Deadshot'],
//   },
//   {
//     imageUrl:
//       'https://www.comixasylum.com/wp-content/uploads/2021/03/BM_UL_Cv4_Jorge_Molina-768x1181.jpg',
//     publisher: 'DC comics',
//     title: 'Camrus Johnson Pens Batman: Urban Legends #4 Story',
//     characters: ['Batman'],
//   },
//   {
//     imageUrl: 'https://d1466nnw0ex81e.cloudfront.net/n_iv/600/1345263.jpg',
//     publisher: 'DC comics',
//     title: 'Batwoman (2011 2nd Series) #19A',
//     reviewCount: 56,
//     rating: 4,
//     characters: ['Batwoman'],
//   },
//   {
//     imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/91WSMdnifFL.jpg',
//     publisher: 'DC comics',
//     title: 'Batman: Three Jokers',
//     reviewCount: 3621,
//     rating: 5,
//     characters: ['Batman', 'Joker'],
//   },
//   {
//     imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/81ix2iemSzL.jpg',
//     publisher: 'DC comics',
//     title: 'Batman: Last Knight on Earth',
//     reviewCount: 2086,
//     rating: 5,
//     characters: ['Batman'],
//   },
//   {
//     imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/91sf28vaugL.jpg',
//     publisher: 'DC comics',
//     title: 'Flashpoint: The 10th Anniversary Omnibus',
//     reviewCount: 15,
//     rating: 4,
//     characters: ['Flash'],
//   },
//   {
//     imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/A1jJPzBOukL.jpg',
//     publisher: 'DC comics',
//     title: 'Superman Vol. 3: The Truth Revealed',
//     reviewCount: 116,
//     rating: 5,
//     characters: ['Superman'],
//   },
//   {
//     imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/81ZWpnAQt7L.jpg',
//     publisher: 'DC comics',
//     title: 'Superman/Batman Omnibus Vol. 1',
//     reviewCount: 116,
//     rating: 5,
//     characters: ['Superman', 'Batman'],
//   },
//   {
//     imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/A1-bTmKIA5L.jpg',
//     publisher: 'DC comics',
//     title: 'Aquaman by Geoff Johns Omnibus',
//     reviewCount: 431,
//     rating: 5,
//     characters: ['Aquaman', 'Batman'],
//   },
//   {
//     imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/A12Zm1Dhs3L.jpg',
//     publisher: 'DC comics',
//     title: "Harley Quinn's Greatest Hits",
//     reviewCount: 182,
//     rating: 5,
//     characters: ['Harley Quinn'],
//   },
//   {
//     imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/81d47290WgL.jpg',
//     publisher: 'Marvel comics',
//     title: "Marvel's SPIDER-MAN: Hostile Takeover",
//     reviewCount: 748,
//     rating: 5,
//     characters: ['Spider-man'],
//   },
//   {
//     imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/61Ip8R1J5bL.jpg',
//     publisher: 'Marvel comics',
//     title: 'Tony Stark: Iron Man Vol. 1: Self-Made Man',
//     reviewCount: 104,
//     rating: 4,
//     characters: ['Iron Man'],
//   },
//   {
//     imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/91spPzMHYgL.jpg',
//     publisher: 'Marvel comics',
//     title: 'Immortal Hulk Vol. 3',
//     characters: ['Hulk'],
//   },
//   {
//     imageUrl: 'https://m.media-amazon.com/images/I/61mabGLR+IL.jpg',
//     publisher: 'Marvel comics',
//     title: 'Vision and the Scarlet Witch (1985-1986) #1',
//     reviewCount: 6,
//     rating: 4,
//     characters: ['Scarlet witch', 'Vision'],
//   },
//   {
//     imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/91fGZ4aZFVL.jpg',
//     publisher: 'Marvel comics',
//     title: 'Captain America Epic Collection: Captain America Lives Again',
//     reviewCount: 57,
//     rating: 5,
//     characters: ['Captain America'],
//   },
//   {
//     imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/511bJW4YkPL.jpg',
//     publisher: 'Marvel comics',
//     title: 'Black Widow Epic Collection: Beware the Black Widow',
//     reviewCount: 99,
//     rating: 5,
//     characters: ['Black Widow'],
//   },
//   {
//     imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/61cmOABUNcL.jpg',
//     publisher: 'DC comics',
//     title: 'Venom by Donny Cates Vol. 1: Rex (Venom (2018), 1)',
//     reviewCount: 714,
//     rating: 4,
//     characters: ['Venom'],
//   },
//   {
//     imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/51xxZTkQgsL.jpg',
//     publisher: 'DC comics',
//     title: 'Spider-Man: Birth of Venom',
//     reviewCount: 544,
//     rating: 5,
//     characters: ['Venom', 'Spider-man'],
//   },
//   {
//     imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/51g-gOK-R7L.jpg',
//     publisher: 'Marvel comics',
//     title: 'Thanos Wins by Donny Cates',
//     reviewCount: 317,
//     rating: 5,
//     characters: ['Thanos', 'Hulk'],
//   },
//   {
//     imageUrl: 'https://m.media-amazon.com/images/I/51m8Re89hHL.jpg',
//     publisher: 'Marvel comics',
//     title:
//       'Doctor Strange Epic Collection: Master Of The Mystic Arts (Strange Tales (1951-1968) Book 1)',
//     reviewCount: 72,
//     rating: 5,
//     characters: ['Doctor Strange'],
//   },
//   {
//     imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/91cak42Xs5L.jpg',
//     publisher: 'Marvel comics',
//     title: 'Thor by Walt Simonson Omnibus (Mighty Thor)',
//     reviewCount: 136,
//     rating: 4,
//     characters: ['Thor'],
//   },
//   {
//     imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/51gGusAquLL.jpg',
//     publisher: 'Marvel comics',
//     title: 'Spider-Man / Deadpool Volume 1',
//     reviewCount: 573,
//     rating: 4,
//     characters: ['Deadpool', 'Spider-Man'],
//   },
//   {
//     imageUrl: 'https://m.media-amazon.com/images/I/61RnWfTooxL.jpg',
//     publisher: 'DC comics',
//     title: 'Batman: Arkham: Poison Ivy (Batman (1940-2011) Book 5',
//     reviewCount: 107,
//     rating: 4,
//     characters: ['Batman', 'Poison Ivy'],
//   },
//   {
//     imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/51yJcVOH5sL.jpg',
//     publisher: 'Marvel comics',
//     title: 'Wolverine: Enemy of the State',
//     reviewCount: 178,
//     rating: 4,
//     characters: ['Wolverine'],
//   },
// ];
